SUBROUTINE CHKOVR(TICTAC, OVER, WINNER)
! C
! C CHECK IF TIC-TAC-TOE IS OVER AND DETERMINE WINNER (IF ANY)
! C
! C ARGUMENT DEFINITIONS --
! C C C C C C
! INPUT ARGUMENTS
!   TICTAC - REPRESENTS THE CURRENT STATE OF THE BOARD GAME
! OUTPUT ARGUMENTS
!   OVER - INDICATES WHETHER OR NOT GAME IS OVER
!   WINNER - INDICATES THE WINNER (O OR X) OR A DRAW (D)
  CHARACTER * 1 TICTAC(3,3), WINNER
      LOGICAL OVER
! C
! C SUBROUTINE PARAMETERS
      CHARACTER * 1 BLANK, DRAW
      PARAMETER (BLANK = ' ', DRAW = 'D')
! C
! C FUNCTIONS USED
      LOGICAL SAME
! C
! C LOCAL VARIABLES
      LOGICAL DSAME
      INTEGER IR, IC
! C ASSUME GAME IS OVER AT START
      OVER = .TRUE.
! C
! C CHECK FOR A WINNER
! C CHECK ROWS FOR A WINNER
      DO 10 IR=1, 3
      IF (SAME(TICTAC(IR,1), TICTAC(IR,2), TICTAC(IR,3))) THEN
          WINNER = TICTAC(IR,1)
RETURN ENDIF
   10 CONTINUE
! C NO WINNER BY ROWS, CHECK COLUMNS FOR A WINNER
      DO 20 IC=1, 3
      IF (SAME(TICTAC(1,IC), TICTAC(2,IC), TICTAC(3,IC))) THEN
          WINNER = TICTAC(I,IC)
RETURN ENDIF
   20 CONTINUE
! C NO WINNER BY ROWS OR COLUMNS, CHECK DIAGONALS FOR A WINNER
DSAME = SAME(TICTAC(1,1), TICTAC(2,2), TICTAC(3,3))
     Z .OR. SAME(TICTAC(1,3), TICTAC(2,2), TICTAC(3,1))
      IF (DSAME) THEN
          WINNER = TICTAC(2,2)
          RETURN
      END IF
! C NO WINNER AT ALL. SEE IF GAME IS A DRAW
! C CHECK EACH ROW FOR AN EMPTY SPACE
      DO 40 IR = 1, 3
      DO 45 IC = 1, 3
      IF (TICTAC(IR,IC) .EQ. BLANK) THEN
          OVER = .FALSE.
RETURN END IF
45 CONTINUE
40 CONTINUE
! C NO BLANK FOUND, GRAME IS A DRAW
      WINNER = DRAW
! C
RETURN
END