*L6_1.x68 
*Dominick Hera
*26/10/17


        ORG     $8000
START	LEA	S,A1
		TRAP	#2
		MOVEA.L	#S,A1
TOP		MOVE.B	(A1)+,D3
		CMP.B	#0,D3
		BEQ		QUIT
CHECKLO	CMP.B   #'a',D3
        BLO		CHECKUP
		CMP.B	#'z',D3
		BHI		CHECKUP
		BRA		ISLOW
CHECKUP	CMP.B	#'A',D3
		BLO	ISPUNC
		CMP.B	#'Z',D3
		BHI		ISPUNC
		BRA		ISUPPER
ISLOW	ADD.B	#1,D0
		BRA		LOOP
ISUPPER	ADD.B	#1,D1
		BRA		LOOP
ISPUNC	ADD.B	#1,D2
		BRA		LOOP
LOOP	BRA		TOP
QUIT	TRAP	#14

	ORG	$9000
S	DC.B	'Na na na na BATMAN!!!!',0
	END	START