CFLAGS = -std=c99 -Wall
EXE = run

all: $(EXE)

$(EXE): run.o functions.o BIN
	gcc run.o functions.o -o ./bin/$(EXE)

BIN:
	if [ ! -d "bin" ]; then mkdir bin; fi;


run.o: ./src/run.c
	gcc -c $(CFLAGS) ./src/run.c -Iinclude

functions.o: ./src/functions.c
	gcc -c $(CFLAGS) ./src/functions.c -Iinclude

clean:
	rm *.o
